databases:
  - name: task manager
    databaseNam: mydb
    user: mydb_hiy6_user

services:
  - type: web
    name: task manager
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn task_manager.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
